"use client";

import { Check, Edit3, Plus, Trash2 } from "lucide-react";
import { useMutation } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";
import { api } from "@/lib/api-client";

type Profile = { id: string; name: string; avatar: string | null };
const avatars = ["adinkra", "kente", "coast", "savannah", "highlife", "market"] as const;
const palettes: Record<string, string> = { adinkra: "from-amber-700 to-orange-400", kente: "from-red-700 to-amber-400", coast: "from-sky-700 to-cyan-300", savannah: "from-green-800 to-lime-400", highlife: "from-violet-800 to-fuchsia-400", market: "from-rose-700 to-orange-300" };

export function ProfileManager({ initialProfiles, activeId }: { initialProfiles: Profile[]; activeId?: string }) {
  const router = useRouter(); const [profiles, setProfiles] = useState(initialProfiles); const [editing, setEditing] = useState<Profile | "new" | null>(null); const [manage, setManage] = useState(false);
  const selectMutation = useMutation({ mutationFn: (profileId: string) => api<Profile>("/profiles/select", { method: "POST", body: JSON.stringify({ profileId }) }), onSuccess: () => { router.push("/"); router.refresh(); }, onError: (error) => toast.error(error.message) });
  const saveMutation = useMutation({ mutationFn: ({ profile, name, avatar }: { profile: Profile | "new"; name: string; avatar: string }) => api<Profile>(profile === "new" ? "/profiles" : `/profiles/${profile.id}`, { method: profile === "new" ? "POST" : "PATCH", body: JSON.stringify({ name, avatar }) }), onSuccess: (saved, variables) => { setProfiles((items) => variables.profile === "new" ? [...items, saved] : items.map((item) => item.id === saved.id ? saved : item)); setEditing(null); toast.success("Profile saved."); router.refresh(); }, onError: (error) => toast.error(error.message) });
  const deleteMutation = useMutation({ mutationFn: (id: string) => api<{ id: string }>(`/profiles/${id}`, { method: "DELETE" }), onSuccess: ({ id }) => { setProfiles((items) => items.filter((item) => item.id !== id)); toast.success("Profile deleted."); router.refresh(); }, onError: (error) => toast.error(error.message) });
  return <div><div className="mt-12 grid grid-cols-2 gap-8 sm:grid-cols-3 lg:grid-cols-5">{profiles.map((profile) => <div key={profile.id} className="text-center"><button disabled={selectMutation.isPending} onClick={() => manage ? setEditing(profile) : selectMutation.mutate(profile.id)} className="group relative mx-auto block"><span className={`grid aspect-square w-32 place-items-center overflow-hidden rounded-xl border-4 bg-gradient-to-br ${palettes[profile.avatar ?? "adinkra"]} text-4xl font-black text-white shadow-lg transition group-hover:-translate-y-1 group-hover:shadow-xl sm:w-36`}>{profile.name.slice(0, 1).toUpperCase()}</span>{profile.id === activeId ? <span className="absolute -right-2 -top-2 grid h-8 w-8 place-items-center rounded-full bg-green-600 text-white shadow"><Check className="h-4 w-4" /></span> : null}{manage ? <span className="absolute inset-0 grid place-items-center rounded-xl bg-black/40 text-white"><Edit3 /></span> : null}</button><h2 className="mt-4 font-bold">{profile.name}</h2><p className="mt-1 text-xs text-muted-foreground">{profile.id === activeId ? "Active profile" : "Viewer profile"}</p>{manage ? <button disabled={profiles.length <= 1 || deleteMutation.isPending} onClick={() => { if (confirm(`Delete ${profile.name}?`)) deleteMutation.mutate(profile.id); }} className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-destructive disabled:opacity-30"><Trash2 className="h-3 w-3" />Delete</button> : null}</div>)}{profiles.length < 5 ? <button onClick={() => setEditing("new")} className="mx-auto text-center"><span className="grid aspect-square w-32 place-items-center rounded-xl border-2 border-dashed bg-white text-muted-foreground sm:w-36"><Plus className="h-9 w-9" /></span><span className="mt-4 block font-bold">Add Profile</span><span className="mt-1 block text-xs text-muted-foreground">Up to 5 total</span></button> : null}</div><div className="mt-12 flex justify-center"><button onClick={() => setManage((value) => !value)} className="inline-flex items-center gap-2 rounded-md border bg-white px-6 py-3 font-bold"><Edit3 className="h-4 w-4" />{manage ? "Done Managing" : "Manage Profiles"}</button></div>{editing ? <ProfileDialog profile={editing} pending={saveMutation.isPending} onClose={() => setEditing(null)} onSave={(name, avatar) => saveMutation.mutate({ profile: editing, name, avatar })} /> : null}</div>;
}

function ProfileDialog({ profile, pending, onClose, onSave }: { profile: Profile | "new"; pending: boolean; onClose: () => void; onSave: (name: string, avatar: string) => void }) {
  const [name, setName] = useState(profile === "new" ? "" : profile.name); const [avatar, setAvatar] = useState(profile === "new" ? "adinkra" : profile.avatar ?? "adinkra");
  return <div role="dialog" aria-modal="true" className="fixed inset-0 z-[70] grid place-items-center bg-black/50 p-4 backdrop-blur-sm"><form onSubmit={(event) => { event.preventDefault(); onSave(name, avatar); }} className="w-full max-w-md rounded-xl bg-white p-6 shadow-2xl"><h2 className="text-2xl font-extrabold">{profile === "new" ? "Add Profile" : "Edit Profile"}</h2><label className="mt-6 block text-sm font-bold">Profile name<input value={name} onChange={(event) => setName(event.target.value)} maxLength={40} required className="mt-2 h-11 w-full rounded-md border px-3 font-normal" /></label><fieldset className="mt-5"><legend className="text-sm font-bold">Avatar</legend><div className="mt-3 grid grid-cols-6 gap-2">{avatars.map((item) => <button type="button" key={item} onClick={() => setAvatar(item)} aria-label={item} className={`aspect-square rounded-md bg-gradient-to-br ${palettes[item]} ${avatar === item ? "ring-2 ring-primary ring-offset-2" : ""}`} />)}</div></fieldset><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-md border px-4 py-2 font-semibold">Cancel</button><button disabled={pending} className="rounded-md bg-primary px-4 py-2 font-bold text-white disabled:opacity-60">{pending ? "Saving…" : "Save Profile"}</button></div></form></div>;
}
