import { Search } from "lucide-react";
import Link from "next/link";
import { ContentCard } from "@/components/catalogue/content-card";
import { ContentType } from "@/generated/prisma/enums";
import { getCatalogueFacets, getCataloguePage, parseCatalogueQuery } from "@/lib/catalogue";
import { cn } from "@/lib/utils";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;
const types = [["All Formats", ""], ["Movies", ContentType.MOVIE], ["TV Series", ContentType.SERIES], ["Documentaries", ContentType.DOCUMENTARY], ["Cultural & Folklore", ContentType.CULTURAL_PROGRAMME], ["Lifestyle", ContentType.LIFESTYLE_PROGRAMME]] as const;

export async function CataloguePage({ searchParams, route = "/browse" }: { searchParams: SearchParams; route?: "/browse" | "/search" }) {
  const raw = await searchParams; const query = parseCatalogueQuery(raw); const [{ items, pagination }, facets] = await Promise.all([getCataloguePage(query), getCatalogueFacets()]);
  const href = (patch: Record<string, string | number | undefined>) => { const params = new URLSearchParams(); const values = { ...query, ...patch }; Object.entries(values).forEach(([key, value]) => { if (value !== undefined && value !== "" && !(key === "page" && value === 1) && !(key === "pageSize" && value === 20)) params.set(key, String(value)); }); return `${route}?${params}`; };
  return <>
    <section className="border-b bg-[radial-gradient(circle_at_10%_20%,#dcfce7,transparent_34%),radial-gradient(circle_at_90%_10%,#fef3c7,transparent_30%),#eef3ff]"><div className="gv-container py-12 text-center md:py-16"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-slate-600 shadow-sm">Ghanaian film &amp; heritage registry</span><h1 className="mx-auto mt-4 max-w-2xl text-3xl font-black tracking-tight md:text-5xl">Discover <span className="text-primary">Ghanaian</span> Stories &amp; Cinematic Heritage</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Explore acclaimed cinema, folklore archives, urban drama, documentaries, and highlife soundtracks.</p><form action={route} className="relative mx-auto mt-7 max-w-2xl"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-primary" /><input name="q" defaultValue={query.q} placeholder="Search titles, cast, stories…" className="h-14 w-full rounded-xl border bg-white pl-12 pr-28 shadow-sm" /><button className="absolute right-2 top-2 h-10 rounded-lg bg-primary px-5 text-sm font-bold text-white">Search</button></form></div></section>
    <section className="border-b bg-white"><div className="gv-container flex gap-2 overflow-x-auto py-3">{types.map(([label, value]) => <Link key={label} href={href({ type: value || undefined, page: 1 })} className={cn("whitespace-nowrap rounded-md px-4 py-2 text-xs font-semibold", query.type === value || !query.type && !value ? "bg-primary text-white" : "bg-muted text-slate-700")}>{label}</Link>)}</div></section>
    <section className="gv-container py-8"><form action={route} className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-2 lg:grid-cols-5"><input type="hidden" name="q" value={query.q} /><input type="hidden" name="type" value={query.type ?? ""} /><Filter name="genre" label="All genres" value={query.genre} options={facets.genres.map((item) => [item.slug, item.name])} /><Filter name="language" label="All languages" value={query.language} options={facets.languages.map((item) => [item.code, item.name])} /><Filter name="classification" label="Any classification" value={query.classification} options={facets.classifications.map((item) => [item.slug, item.name])} /><Filter name="sort" label="Featured first" value={query.sort} options={[["featured", "Featured first"], ["newest", "Newest"], ["oldest", "Oldest"], ["title-asc", "Title A–Z"], ["title-desc", "Title Z–A"]]} /><button className="rounded-md bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">Apply filters</button></form><div className="mt-7 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-primary">Ghanaian Film Catalogue</p><h2 className="mt-1 text-xl font-extrabold">{pagination.total} published title{pagination.total === 1 ? "" : "s"}</h2></div><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-800">Curated catalogue</span></div>{items.length ? <div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{items.map((item) => <ContentCard key={item.id} item={item} />)}</div> : <div className="mt-8 rounded-xl border bg-white p-12 text-center"><h2 className="text-xl font-bold">No matching GhanaVerse titles</h2><p className="mt-2 text-sm text-muted-foreground">Try removing a filter or using a broader search.</p><Link href={route} className="mt-5 inline-block text-sm font-bold text-primary">Reset catalogue</Link></div>}<nav className="mt-10 flex items-center justify-between border-t pt-5 text-sm"><span className="text-muted-foreground">Page {pagination.page} of {pagination.totalPages}</span><div className="flex gap-2">{pagination.page > 1 ? <Link className="rounded-md border bg-white px-4 py-2 font-semibold" href={href({ page: pagination.page - 1 })}>Previous</Link> : null}{pagination.page < pagination.totalPages ? <Link className="rounded-md bg-primary px-4 py-2 font-semibold text-white" href={href({ page: pagination.page + 1 })}>Next</Link> : null}</div></nav></section>
  </>;
}

function Filter({ name, label, value, options }: { name: string; label: string; value?: string; options: Array<readonly [string, string] | [string, string]> }) { return <select name={name} defaultValue={value ?? ""} aria-label={label} className="h-11 rounded-md border bg-white px-3 text-sm"><option value="">{label}</option>{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select>; }
