"use client";
import { useState } from "react";
import { toast } from "sonner";

type EditorContent = { id: string; title: string; description: string; shortDescription: string; posterUrl: string | null; backdropUrl: string | null; publicationStatus: "DRAFT" | "PUBLISHED" | "UNPUBLISHED"; trailer?: { youtubeVideoId: string } | null };
export function ContentEditor({ content }: { content: EditorContent }) {
  const [saving, setSaving] = useState(false); const [status, setStatus] = useState(content.publicationStatus);
  async function save(form: FormData) { setSaving(true); const response = await fetch(`/api/admin/content/${content.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: form.get("title"), shortDescription: form.get("shortDescription"), description: form.get("description"), posterUrl: form.get("posterUrl"), backdropUrl: form.get("backdropUrl"), trailerUrl: form.get("trailerUrl"), publicationStatus: status }) }); const body = await response.json(); setSaving(false); if (!response.ok) { toast.error(body.message ?? "Content could not be saved."); return; } toast.success("Content updated."); }
  return <form action={save} className="mt-8 grid gap-6 rounded-xl border bg-card p-6"><label className="grid gap-2 text-sm font-bold">Title<input name="title" required defaultValue={content.title} className="rounded-md border bg-background px-3 py-2 font-normal" /></label><label className="grid gap-2 text-sm font-bold">Short description<input name="shortDescription" required defaultValue={content.shortDescription} className="rounded-md border bg-background px-3 py-2 font-normal" /></label><label className="grid gap-2 text-sm font-bold">Description<textarea name="description" required defaultValue={content.description} rows={8} className="rounded-md border bg-background px-3 py-2 font-normal" /></label><div className="grid gap-6 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Poster URL<input name="posterUrl" defaultValue={content.posterUrl ?? ""} className="rounded-md border bg-background px-3 py-2 font-normal" /></label><label className="grid gap-2 text-sm font-bold">Backdrop URL<input name="backdropUrl" defaultValue={content.backdropUrl ?? ""} className="rounded-md border bg-background px-3 py-2 font-normal" /></label></div><label className="grid gap-2 text-sm font-bold">Trailer YouTube URL or ID<input name="trailerUrl" defaultValue={content.trailer?.youtubeVideoId ?? ""} className="rounded-md border bg-background px-3 py-2 font-normal" /></label><label className="grid gap-2 text-sm font-bold">Publication status<select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className="rounded-md border bg-background px-3 py-2 font-normal"><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="UNPUBLISHED">Unpublished</option></select></label><button disabled={saving} className="w-fit rounded-md bg-primary px-5 py-3 font-bold text-primary-foreground disabled:opacity-60">{saving ? "Saving…" : "Save content"}</button></form>;
}
