import Link from "next/link";
import type { ReactNode } from "react";
import { Brand } from "@/components/layout/brand";
import { ViewerNavigation } from "@/components/layout/viewer-navigation";

export function ViewerShell({ children }: { children: ReactNode }) {
  return <div className="min-h-screen bg-background"><header className="sticky top-0 z-40 border-b bg-white/95 backdrop-blur"><div className="gv-container flex h-16 items-center gap-7"><Brand /><ViewerNavigation /></div><div className="gv-kente-line" /></header><main>{children}</main><footer className="mt-20 border-t bg-white"><div className="gv-container grid gap-10 py-12 sm:grid-cols-2 lg:grid-cols-4"><div><Brand /><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">Celebrating Ghanaian cinema, cultural archives, highlife rhythms, and modern episodic storytelling.</p><span className="mt-4 inline-flex rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-800">Curated from Accra &amp; Kumasi</span></div><FooterColumn title="Discover" links={[["GhanaVerse Home", "/"], ["Browse Catalogue", "/browse"], ["Search", "/search"]]} /><FooterColumn title="Your GhanaVerse" links={[["Viewer Profiles", "/profiles"], ["My Library", "/library"], ["Account", "/account"]]} /><div><h2 className="text-xs font-bold uppercase tracking-[.14em]">Platform</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">Authentic Ghanaian stories, presented with care and clear media provenance.</p></div></div><div className="gv-container border-t py-5 text-xs text-muted-foreground">© 2026 GhanaVerse Media. Ghanaian cinema first.</div></footer></div>;
}

function FooterColumn({ title, links }: { title: string; links: Array<[string, string]> }) { return <div><h2 className="text-xs font-bold uppercase tracking-[.14em]">{title}</h2><nav className="mt-4 grid gap-3">{links.map(([label, href]) => <Link key={href} href={href} className="text-sm text-muted-foreground hover:text-primary">{label}</Link>)}</nav></div>; }
