import { Mail, UserRound, Users } from "lucide-react";
import Link from "next/link";
import { SignOutButton } from "@/components/auth/sign-out-button";
import { requireUserPage } from "@/lib/auth/access";
import { getPrisma } from "@/lib/prisma";
import { getActiveProfile } from "@/lib/profiles";

export default async function AccountPage() {
  const { user } = await requireUserPage("/account"); const [profiles, active] = await Promise.all([getPrisma().viewerProfile.findMany({ where: { userId: user.id }, orderBy: { createdAt: "asc" } }), getActiveProfile(user.id)]);
  return <section className="gv-container max-w-5xl py-10 md:py-14"><p className="text-sm text-muted-foreground"><Link href="/">Home</Link> / Account</p><div className="mt-5"><h1 className="text-4xl font-black tracking-tight">Account</h1><p className="mt-2 max-w-2xl text-muted-foreground">Manage your GhanaVerse identity and viewer profiles.</p></div><section className="mt-8 rounded-xl border bg-white p-5 md:p-7"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-amber-100 text-primary"><UserRound className="h-5 w-5" /></span><div><h2 className="font-bold">Personal Details</h2><p className="text-xs text-muted-foreground">From your verified GhanaVerse account</p></div></div></div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-lg bg-muted p-4"><dt className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Full name</dt><dd className="mt-2 flex items-center gap-2 font-bold"><UserRound className="h-4 w-4 text-primary" />{user.name}</dd></div><div className="rounded-lg bg-muted p-4"><dt className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Email address</dt><dd className="mt-2 flex items-center gap-2 font-bold"><Mail className="h-4 w-4 text-primary" />{user.email}</dd></div></dl></section><section className="mt-6 rounded-xl border bg-white p-5 md:p-7"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-green-100 text-green-700"><Users className="h-5 w-5" /></span><div><h2 className="font-bold">Viewer Profiles ({profiles.length} of 5)</h2><p className="text-xs text-muted-foreground">Active profile: {active?.name ?? "None"}</p></div></div><Link href="/profiles" className="text-sm font-bold text-primary">Manage Profiles →</Link></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{profiles.map((profile) => <div key={profile.id} className="rounded-lg bg-muted p-4"><span className="grid h-11 w-11 place-items-center rounded-full bg-primary text-lg font-black text-white">{profile.name[0]?.toUpperCase()}</span><h3 className="mt-3 font-bold">{profile.name}</h3><p className="text-xs text-muted-foreground">{profile.id === active?.id ? "Active profile" : "Viewer profile"}</p></div>)}</div></section><section className="mt-6 flex flex-col justify-between gap-4 rounded-xl border bg-white p-5 sm:flex-row sm:items-center"><div><h2 className="font-bold">Session Controls</h2><p className="mt-1 text-sm text-muted-foreground">Sign out safely from this browser.</p></div><SignOutButton /></section></section>;
}
